/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"github.com/faroshq/faros-hub/pkg/client/informers/externalversions/internalinterfaces"
)

type ClusterInterface interface {
// Agents returns a AgentClusterInformer
	Agents() AgentClusterInformer
// Registrations returns a RegistrationClusterInformer
	Registrations() RegistrationClusterInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new ClusterInterface.
func New(f internalinterfaces.SharedInformerFactory, tweakListOptions internalinterfaces.TweakListOptionsFunc) ClusterInterface {
	return &version{factory: f, tweakListOptions: tweakListOptions}
}

// Agents returns a AgentClusterInformer
func (v *version) Agents() AgentClusterInformer {
	return &agentClusterInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
// Registrations returns a RegistrationClusterInformer
func (v *version) Registrations() RegistrationClusterInformer {
	return &registrationClusterInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
type Interface interface {
// Agents returns a AgentInformer
	Agents() AgentInformer
// Registrations returns a RegistrationInformer
	Registrations() RegistrationInformer
}

type scopedVersion struct {
	factory          internalinterfaces.SharedScopedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace string
}

// New returns a new ClusterInterface.
func NewScoped(f internalinterfaces.SharedScopedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &scopedVersion{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Agents returns a AgentInformer
func (v *scopedVersion) Agents() AgentInformer {
	return &agentScopedInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
// Registrations returns a RegistrationInformer
func (v *scopedVersion) Registrations() RegistrationInformer {
	return &registrationScopedInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

