apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: systemds.services.plugins.faros.sh
spec:
  reference:
    workspace:
      exportName: v20221123.systemds.services.plugins.faros.sh
      path: root:faros:service:plugins

