apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: access.faros.sh
spec:
  reference:
    workspace:
      exportName: access.faros.sh
      path: root:compute:controllers
  permissionClaims:
  - group: access.faros.sh
    resource: kubeconfigrequests
    state: Accepted
