# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- access.faros.sh_requests.yaml
- edge.faros.sh_agents.yaml
- edge.faros.sh_registrations.yaml
- plugins.faros.sh_requests.yaml
- plugins.faros.sh_bindings.yaml
- tenancy.faros.sh_workspaces.yaml
- tenancy.faros.sh_users.yaml
