/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"github.com/kcp-dev/logicalcluster/v2"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"

	"k8s.io/apimachinery/pkg/runtime/schema"
	"context"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	pluginsv1alpha1 "github.com/faroshq/faros-hub/pkg/apis/plugins/v1alpha1"

	"k8s.io/apimachinery/pkg/watch"

	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/testing"

	"k8s.io/apimachinery/pkg/types"

	pluginsv1alpha1client "github.com/faroshq/faros-hub/pkg/client/clientset/versioned/typed/plugins/v1alpha1"
)

var requestsResource = schema.GroupVersionResource{Group: "plugins.faros.sh", Version: "v1alpha1", Resource: "requests"}
var requestsKind = schema.GroupVersionKind{Group: "plugins.faros.sh", Version: "v1alpha1", Kind: "Request"}

type requestsClusterClient struct {
	*kcptesting.Fake
}

// Cluster scopes the client down to a particular cluster.
func (c *requestsClusterClient) Cluster(cluster logicalcluster.Name) pluginsv1alpha1client.RequestInterface {
	if cluster == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &requestsClient{Fake: c.Fake, Cluster: cluster}
}


// List takes label and field selectors, and returns the list of Requests that match those selectors across all clusters.
func (c *requestsClusterClient) List(ctx context.Context, opts metav1.ListOptions) (*pluginsv1alpha1.RequestList, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootListAction(requestsResource, requestsKind, logicalcluster.Wildcard, opts), &pluginsv1alpha1.RequestList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &pluginsv1alpha1.RequestList{ListMeta: obj.(*pluginsv1alpha1.RequestList).ListMeta}
	for _, item := range obj.(*pluginsv1alpha1.RequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested Requests across all clusters.
func (c *requestsClusterClient) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.InvokesWatch(kcptesting.NewRootWatchAction(requestsResource, logicalcluster.Wildcard, opts))
}
type requestsClient struct {
	*kcptesting.Fake
	Cluster logicalcluster.Name
	
}


func (c *requestsClient) Create(ctx context.Context, request *pluginsv1alpha1.Request, opts metav1.CreateOptions) (*pluginsv1alpha1.Request, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootCreateAction(requestsResource, c.Cluster, request), &pluginsv1alpha1.Request{})
	if obj == nil {
		return nil, err
	}
	return obj.(*pluginsv1alpha1.Request), err
}

func (c *requestsClient) Update(ctx context.Context, request *pluginsv1alpha1.Request, opts metav1.UpdateOptions) (*pluginsv1alpha1.Request, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootUpdateAction(requestsResource, c.Cluster, request), &pluginsv1alpha1.Request{})
	if obj == nil {
		return nil, err
	}
	return obj.(*pluginsv1alpha1.Request), err
}

func (c *requestsClient) UpdateStatus(ctx context.Context, request *pluginsv1alpha1.Request, opts metav1.UpdateOptions) (*pluginsv1alpha1.Request, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootUpdateSubresourceAction(requestsResource, c.Cluster, "status", request), &pluginsv1alpha1.Request{})
	if obj == nil {
		return nil, err
	}
	return obj.(*pluginsv1alpha1.Request), err
}

func (c *requestsClient) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.Invokes(kcptesting.NewRootDeleteActionWithOptions(requestsResource, c.Cluster, name, opts), &pluginsv1alpha1.Request{})
	return err
}

func (c *requestsClient) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := kcptesting.NewRootDeleteCollectionAction(requestsResource, c.Cluster, listOpts)

	_, err := c.Fake.Invokes(action, &pluginsv1alpha1.RequestList{})
	return err
}

func (c *requestsClient) Get(ctx context.Context, name string, options metav1.GetOptions) (*pluginsv1alpha1.Request, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootGetAction(requestsResource, c.Cluster, name), &pluginsv1alpha1.Request{})
	if obj == nil {
		return nil, err
	}
	return obj.(*pluginsv1alpha1.Request), err
}

// List takes label and field selectors, and returns the list of Requests that match those selectors.
func (c *requestsClient) List(ctx context.Context, opts metav1.ListOptions) (*pluginsv1alpha1.RequestList, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootListAction(requestsResource, requestsKind, c.Cluster, opts), &pluginsv1alpha1.RequestList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &pluginsv1alpha1.RequestList{ListMeta: obj.(*pluginsv1alpha1.RequestList).ListMeta}
	for _, item := range obj.(*pluginsv1alpha1.RequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

func (c *requestsClient) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.InvokesWatch(kcptesting.NewRootWatchAction(requestsResource, c.Cluster, opts))
}

func (c *requestsClient) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*pluginsv1alpha1.Request, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootPatchSubresourceAction(requestsResource, c.Cluster, name, pt, data, subresources...), &pluginsv1alpha1.Request{})
	if obj == nil {
		return nil, err
	}
	return obj.(*pluginsv1alpha1.Request), err
}
