/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package informers

import (
	"fmt"

	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/tools/cache"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	"github.com/kcp-dev/logicalcluster/v3"

		edgev1alpha1 "github.com/faroshq/faros-hub/pkg/apis/edge/v1alpha1"
	pluginsv1alpha1 "github.com/faroshq/faros-hub/pkg/apis/plugins/v1alpha1"
	tenancyv1alpha1 "github.com/faroshq/faros-hub/pkg/apis/tenancy/v1alpha1"
)

type GenericClusterInformer interface {
	Cluster(logicalcluster.Name) GenericInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() kcpcache.GenericClusterLister
}


type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}


type genericClusterInformer struct {
	informer kcpcache.ScopeableSharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return f.informer
}

// Lister returns the GenericClusterLister.
func (f *genericClusterInformer) Lister() kcpcache.GenericClusterLister {
	return kcpcache.NewGenericClusterLister(f.Informer().GetIndexer(), f.resource)
}

// Cluster scopes to a GenericInformer.
func (f *genericClusterInformer) Cluster(clusterName logicalcluster.Name) GenericInformer {
	return &genericInformer{
		informer: f.Informer().Cluster(clusterName),
		lister:   f.Lister().ByCluster(clusterName),
	}
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	lister   cache.GenericLister
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return f.lister
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericClusterInformer, error) {
	switch resource {
	// Group=edge.faros.sh, Version=V1alpha1
	case edgev1alpha1.SchemeGroupVersion.WithResource("agents"):
		return &genericClusterInformer{resource: resource.GroupResource(), informer: f.Edge().V1alpha1().Agents().Informer()}, nil
	case edgev1alpha1.SchemeGroupVersion.WithResource("registrations"):
		return &genericClusterInformer{resource: resource.GroupResource(), informer: f.Edge().V1alpha1().Registrations().Informer()}, nil
	// Group=plugins.faros.sh, Version=V1alpha1
	case pluginsv1alpha1.SchemeGroupVersion.WithResource("bindings"):
		return &genericClusterInformer{resource: resource.GroupResource(), informer: f.Plugins().V1alpha1().Bindings().Informer()}, nil
	case pluginsv1alpha1.SchemeGroupVersion.WithResource("plugins"):
		return &genericClusterInformer{resource: resource.GroupResource(), informer: f.Plugins().V1alpha1().Plugins().Informer()}, nil
	case pluginsv1alpha1.SchemeGroupVersion.WithResource("requests"):
		return &genericClusterInformer{resource: resource.GroupResource(), informer: f.Plugins().V1alpha1().Requests().Informer()}, nil
	// Group=tenancy.faros.sh, Version=V1alpha1
	case tenancyv1alpha1.SchemeGroupVersion.WithResource("users"):
		return &genericClusterInformer{resource: resource.GroupResource(), informer: f.Tenancy().V1alpha1().Users().Informer()}, nil
	case tenancyv1alpha1.SchemeGroupVersion.WithResource("workspaces"):
		return &genericClusterInformer{resource: resource.GroupResource(), informer: f.Tenancy().V1alpha1().Workspaces().Informer()}, nil
}

	return nil, fmt.Errorf("no informer found for %v", resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedScopedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=edge.faros.sh, Version=V1alpha1
	case edgev1alpha1.SchemeGroupVersion.WithResource("agents"):
		informer := f.Edge().V1alpha1().Agents().Informer()
		return &genericInformer{lister: cache.NewGenericLister(informer.GetIndexer(), resource.GroupResource()), informer: informer}, nil
	case edgev1alpha1.SchemeGroupVersion.WithResource("registrations"):
		informer := f.Edge().V1alpha1().Registrations().Informer()
		return &genericInformer{lister: cache.NewGenericLister(informer.GetIndexer(), resource.GroupResource()), informer: informer}, nil
	// Group=plugins.faros.sh, Version=V1alpha1
	case pluginsv1alpha1.SchemeGroupVersion.WithResource("bindings"):
		informer := f.Plugins().V1alpha1().Bindings().Informer()
		return &genericInformer{lister: cache.NewGenericLister(informer.GetIndexer(), resource.GroupResource()), informer: informer}, nil
	case pluginsv1alpha1.SchemeGroupVersion.WithResource("plugins"):
		informer := f.Plugins().V1alpha1().Plugins().Informer()
		return &genericInformer{lister: cache.NewGenericLister(informer.GetIndexer(), resource.GroupResource()), informer: informer}, nil
	case pluginsv1alpha1.SchemeGroupVersion.WithResource("requests"):
		informer := f.Plugins().V1alpha1().Requests().Informer()
		return &genericInformer{lister: cache.NewGenericLister(informer.GetIndexer(), resource.GroupResource()), informer: informer}, nil
	// Group=tenancy.faros.sh, Version=V1alpha1
	case tenancyv1alpha1.SchemeGroupVersion.WithResource("users"):
		informer := f.Tenancy().V1alpha1().Users().Informer()
		return &genericInformer{lister: cache.NewGenericLister(informer.GetIndexer(), resource.GroupResource()), informer: informer}, nil
	case tenancyv1alpha1.SchemeGroupVersion.WithResource("workspaces"):
		informer := f.Tenancy().V1alpha1().Workspaces().Informer()
		return &genericInformer{lister: cache.NewGenericLister(informer.GetIndexer(), resource.GroupResource()), informer: informer}, nil
}

	return nil, fmt.Errorf("no informer found for %v", resource)
}

