/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"net/http"

	kcpclient "github.com/kcp-dev/apimachinery/pkg/client"
	"github.com/kcp-dev/logicalcluster/v2"

	"k8s.io/client-go/rest"

	pluginsv1alpha1 "github.com/faroshq/faros-hub/pkg/client/clientset/versioned/typed/plugins/v1alpha1"
)

type PluginsV1alpha1ClusterInterface interface {
	PluginsV1alpha1ClusterScoper
	PluginsClusterGetter
}

type PluginsV1alpha1ClusterScoper interface {
	Cluster(logicalcluster.Name) pluginsv1alpha1.PluginsV1alpha1Interface
}

type PluginsV1alpha1ClusterClient struct {
	clientCache kcpclient.Cache[*pluginsv1alpha1.PluginsV1alpha1Client]
}

func (c *PluginsV1alpha1ClusterClient) Cluster(name logicalcluster.Name) pluginsv1alpha1.PluginsV1alpha1Interface {
	if name == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}
	return c.clientCache.ClusterOrDie(name)
}


func (c *PluginsV1alpha1ClusterClient) Plugins() PluginClusterInterface {
	return &pluginsClusterInterface{clientCache: c.clientCache}
}
// NewForConfig creates a new PluginsV1alpha1ClusterClient for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*PluginsV1alpha1ClusterClient, error) {
	client, err := rest.HTTPClientFor(c)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(c, client)
}

// NewForConfigAndClient creates a new PluginsV1alpha1ClusterClient for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*PluginsV1alpha1ClusterClient, error) {
	cache := kcpclient.NewCache(c, h, &kcpclient.Constructor[*pluginsv1alpha1.PluginsV1alpha1Client]{
		NewForConfigAndClient: pluginsv1alpha1.NewForConfigAndClient,
	})
	if _, err := cache.Cluster(logicalcluster.New("root")); err != nil {
		return nil, err
	}
	return &PluginsV1alpha1ClusterClient{clientCache: cache}, nil
}

// NewForConfigOrDie creates a new PluginsV1alpha1ClusterClient for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *PluginsV1alpha1ClusterClient {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}
