/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	kcpclient "github.com/kcp-dev/apimachinery/pkg/client"
	"github.com/kcp-dev/logicalcluster/v2"
	"context"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"
	pluginsv1alpha1 "github.com/faroshq/faros-hub/pkg/apis/plugins/v1alpha1"


	pluginsv1alpha1client "github.com/faroshq/faros-hub/pkg/client/clientset/versioned/typed/plugins/v1alpha1"
)

// RequestsClusterGetter has a method to return a RequestClusterInterface.
// A group's cluster client should implement this interface.
type RequestsClusterGetter interface {
	Requests() RequestClusterInterface
}

// RequestClusterInterface can operate on Requests across all clusters,
// or scope down to one cluster and return a RequestsNamespacer.
type RequestClusterInterface interface {
	Cluster(logicalcluster.Name) RequestsNamespacer
	List(ctx context.Context, opts metav1.ListOptions) (*pluginsv1alpha1.RequestList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

type requestsClusterInterface struct {
	clientCache kcpclient.Cache[*pluginsv1alpha1client.PluginsV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *requestsClusterInterface) Cluster(name logicalcluster.Name) RequestsNamespacer {
	if name == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &requestsNamespacer{clientCache: c.clientCache, name: name}
}


// List returns the entire collection of all Requests across all clusters. 
func (c *requestsClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*pluginsv1alpha1.RequestList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).Requests(metav1.NamespaceAll).List(ctx, opts)
}

// Watch begins to watch all Requests across all clusters.
func (c *requestsClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).Requests(metav1.NamespaceAll).Watch(ctx, opts)
}
// RequestsNamespacer can scope to objects within a namespace, returning a pluginsv1alpha1client.RequestInterface.
type RequestsNamespacer interface {
	Namespace(string) pluginsv1alpha1client.RequestInterface
}

type requestsNamespacer struct {
	clientCache kcpclient.Cache[*pluginsv1alpha1client.PluginsV1alpha1Client]
	name logicalcluster.Name
}

func (n *requestsNamespacer) Namespace(namespace string) pluginsv1alpha1client.RequestInterface {
	return n.clientCache.ClusterOrDie(n.name).Requests(namespace)
}
