# permissions for end users to edit widgets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: potatoes-editor-role
rules:
- apiGroups:
  - faros.sh
  resources:
  - potatoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - faros.sh
  resources:
  - potatoes/status
  verbs:
  - get
