# permissions for end users to view widgets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: widget-viewer-role
rules:
- apiGroups:
  - faros.sh
  resources:
  - potatoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - faros.sh
  resources:
  - potatoes/status
  verbs:
  - get
