---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - access.faros.sh
  resources:
  - request
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - access.faros.sh
  resources:
  - request/finalizers
  verbs:
  - update
- apiGroups:
  - access.faros.sh
  resources:
  - request/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - edge.faros.sh
  resources:
  - agent
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edge.faros.sh
  resources:
  - agent/finalizers
  verbs:
  - update
- apiGroups:
  - edge.faros.sh
  resources:
  - agent/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - edge.faros.sh
  resources:
  - registrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edge.faros.sh
  resources:
  - registrations/finalizers
  verbs:
  - update
- apiGroups:
  - edge.faros.sh
  resources:
  - registrations/status
  verbs:
  - get
  - patch
  - update
