apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: access.faros.sh
spec:
  latestResourceSchemas:
    - today.requests.access.faros.sh
  permissionClaims:
  - group: ""
    resource: "secrets"
    all: true
  - group: ""
    resource: "serviceaccounts"
    all: true
