apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: access.faros.sh
spec:
  latestResourceSchemas:
    - v20221001.kubeconfigrequests.access.faros.sh
  permissionClaims:
    - group: "access.faros.sh"
      resource: "kubeconfigrequests"
