apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: edge.faros.sh
spec:
  latestResourceSchemas:
  - today.agents.edge.faros.sh
  - today.registrations.edge.faros.sh
  permissionClaims:
  - group: ""
    resource: "secrets"
    all: true
  - group: ""
    resource: "serviceaccounts"
    all: true
  - group: ""
    resource: "configmaps"
    all: true
  - group: "rbac.authorization.k8s.io"
    resource: "roles"
    all: true
  - group: "rbac.authorization.k8s.io"
    resource: "rolebindings"
    all: true
