/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"
	"context"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"
	edgev1alpha1 "github.com/faroshq/faros-hub/pkg/apis/edge/v1alpha1"


	edgev1alpha1client "github.com/faroshq/faros-hub/pkg/client/clientset/versioned/typed/edge/v1alpha1"
)

// AgentsClusterGetter has a method to return a AgentClusterInterface.
// A group's cluster client should implement this interface.
type AgentsClusterGetter interface {
	Agents() AgentClusterInterface
}

// AgentClusterInterface can operate on Agents across all clusters,
// or scope down to one cluster and return a AgentsNamespacer.
type AgentClusterInterface interface {
	Cluster(logicalcluster.Path) AgentsNamespacer
	List(ctx context.Context, opts metav1.ListOptions) (*edgev1alpha1.AgentList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

type agentsClusterInterface struct {
	clientCache kcpclient.Cache[*edgev1alpha1client.EdgeV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *agentsClusterInterface) Cluster(clusterPath logicalcluster.Path) AgentsNamespacer {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &agentsNamespacer{clientCache: c.clientCache, clusterPath: clusterPath}
}


// List returns the entire collection of all Agents across all clusters. 
func (c *agentsClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*edgev1alpha1.AgentList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).Agents(metav1.NamespaceAll).List(ctx, opts)
}

// Watch begins to watch all Agents across all clusters.
func (c *agentsClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).Agents(metav1.NamespaceAll).Watch(ctx, opts)
}
// AgentsNamespacer can scope to objects within a namespace, returning a edgev1alpha1client.AgentInterface.
type AgentsNamespacer interface {
	Namespace(string) edgev1alpha1client.AgentInterface
}

type agentsNamespacer struct {
	clientCache kcpclient.Cache[*edgev1alpha1client.EdgeV1alpha1Client]
	clusterPath logicalcluster.Path
}

func (n *agentsNamespacer) Namespace(namespace string) edgev1alpha1client.AgentInterface {
	return n.clientCache.ClusterOrDie(n.clusterPath).Agents(namespace)
}
