/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/faroshq/faros-hub/pkg/apis/edge/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRegistrations implements RegistrationInterface
type FakeRegistrations struct {
	Fake *FakeEdgeV1alpha1
	ns   string
}

var registrationsResource = schema.GroupVersionResource{Group: "edge.faros.sh", Version: "v1alpha1", Resource: "registrations"}

var registrationsKind = schema.GroupVersionKind{Group: "edge.faros.sh", Version: "v1alpha1", Kind: "Registration"}

// Get takes name of the registration, and returns the corresponding registration object, and an error if there is any.
func (c *FakeRegistrations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Registration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(registrationsResource, c.ns, name), &v1alpha1.Registration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Registration), err
}

// List takes label and field selectors, and returns the list of Registrations that match those selectors.
func (c *FakeRegistrations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RegistrationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(registrationsResource, registrationsKind, c.ns, opts), &v1alpha1.RegistrationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RegistrationList{ListMeta: obj.(*v1alpha1.RegistrationList).ListMeta}
	for _, item := range obj.(*v1alpha1.RegistrationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested registrations.
func (c *FakeRegistrations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(registrationsResource, c.ns, opts))

}

// Create takes the representation of a registration and creates it.  Returns the server's representation of the registration, and an error, if there is any.
func (c *FakeRegistrations) Create(ctx context.Context, registration *v1alpha1.Registration, opts v1.CreateOptions) (result *v1alpha1.Registration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(registrationsResource, c.ns, registration), &v1alpha1.Registration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Registration), err
}

// Update takes the representation of a registration and updates it. Returns the server's representation of the registration, and an error, if there is any.
func (c *FakeRegistrations) Update(ctx context.Context, registration *v1alpha1.Registration, opts v1.UpdateOptions) (result *v1alpha1.Registration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(registrationsResource, c.ns, registration), &v1alpha1.Registration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Registration), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRegistrations) UpdateStatus(ctx context.Context, registration *v1alpha1.Registration, opts v1.UpdateOptions) (*v1alpha1.Registration, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(registrationsResource, "status", c.ns, registration), &v1alpha1.Registration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Registration), err
}

// Delete takes name of the registration and deletes it. Returns an error if one occurs.
func (c *FakeRegistrations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(registrationsResource, c.ns, name, opts), &v1alpha1.Registration{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRegistrations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(registrationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RegistrationList{})
	return err
}

// Patch applies the patch and returns the patched registration.
func (c *FakeRegistrations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Registration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(registrationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Registration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Registration), err
}
