apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- etcd.yaml
- issuer.yaml
- faros.yaml
images:
- name: faros-api
  newName: kind.local/hub-api-173d4ab6bcfe4f66947fbabf99d9de0c
  newTag: 7ad6c6eab39da85cc987b437b4bb8e42c03c36dcd7dd574ac8843a8caf686ad5
