name: image

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true
      - uses: imjasonh/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository }}
      - env:
          auth_token: ${{ secrets.auth_token }}
        run: |
          ko build ./cmd/edge-agent
          ko build ./cmd/hub-controllers
          ko build ./cmd/kubectl-faros
          ko build ./cmd/hub-api
