externalHostname: kcp.dev.faros.sh
kcp:
  image: ghcr.io/kcp-dev/kcp
  tag: latest
  v: "8"
  tokenAuth:
    enabled: true
  hostAliases:
    enabled: true
    values:
    - hostnames:
      - dex.dev.faros.sh
      ip: 127.0.0.1
kcpFrontProxy:
  image: ghcr.io/kcp-dev/kcp
  tag: latest
  v: "2"
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
    paths:
    - path: /(.*)
      pathType: Prefix
      backend:
        service:
          name: kcp-front-proxy
          port:
            number: 8443
    - path: /faros.sh/(.*)
      pathType: Prefix
      backend:
        service:
          name: faros
          port:
            number: 8443
virtualWorkspaces:
  image: ghcr.io/kcp-dev/kcp
  tag: latest
  v: "2"
oidc:
  issuerUrl: https://dex.dev.faros.sh
  clientId: faros
  groupClaim: groups
  usernameClaim: email
  usernamePrefix: "faros-sso:"
  groupsPrefix: "faros-sso:"
  caSecretName: dex-pki-ca
